pipeline{
  agent any
  
   environment {
        JAVA_OPTS = '-Dfile.encoding=UTF-8'
    }

  stages {
      stage('Cehckout'){
        steps{
          checkout scm
        }
      }
      stage('Build') {
        steps {
          script{
             def junitClasspath = 'eclipse/plugins/junit-jupiter-api-5.7.1.jar:eclipse/plugins/junit-platform-console-standalone-1.7.1.jar'
             sh 'mkdir -p classes'
             sh "javac -encoding UTF-8 -cp ${junitClasspath} -d classes Mission2/src/*.java"
          }
        }
      
      stage('Test'){
        steps {
          script{
           // JUnit 5 테스트 실행
                    def junitClasspath = 'classes:eclipse/plugins/junit-jupiter-api-5.7.1.jar:eclipse/plugins/junit-platform-console-standalone-1.7.1.jar'
                    sh "java -Dfile.encoding=UTF-8 -cp ${junitClasspath} org.junit.platform.console.ConsoleLauncher --scan-classpath --classpath classes | tee test_results.txt"

          }
        }
      }
  }
    post {
        always {
          archiveArtifacts'test_results.txt'
        }
       failure{
         echo'Build or test failed'
       }
       success{
         echo'Build and test succeeded'
       }
      }
}
