pipeline{
  agent any
  options {
      skipStagesAfterUnstable()
  }
  stages {
      stage('Cehckout'){
        steps{
          checkout scm
        }
      }
      stage('Build') {
        steps {
          sh 'javac -encoding UTF-8 -d classes swTest/src/**/*.java'
        }
      }
      stage('Test'){
        steps {
          def classpath = "classes;lib/;path/to/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
          bat 'java -cp classes;lib/; path/to/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
          }
        }
      }
     post {
        always {
          archiveArtifacts'test_results.txt'
        }
       failure{
         echo'Build or test failed'
       }
       success{
         echo'Build and test succeeded'
       }
      }
  
}
