pipeline{
  agent any
  options {
      skipStagesAfterUnstable()
  }
  stages {
      stage('Cehckout'){
        steps{
          checkout scm
        }
      }
      stage('Build') {
        steps {
          script{
            def classpath = "classes:lib/;Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
            sh "javac -encoding UTF-8 -cp ${classpath} -d classes swTest/src/**/*.java"
          }
        }
      }
      stage('Test'){
        steps {
          script{
           def classpath = "classes:lib/;Applications/Eclipse.app/Contents/Eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
           sh "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt"
          }
        }
      }
    }
    post {
        always {
          archiveArtifacts'test_results.txt'
        }
       failure{
         echo'Build or test failed'
       }
       success{
         echo'Build and test succeeded'
       }
      }
}
